name: Deploy Frontend

on:
  push:
    branches: [erik/TestWebsiteDeployAction]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Setup node
        uses: ./.github/actions/node-setup

      - name: Build
        run: |
          pnpm run gen
          pnpm run build production

      - name: Create 404.html for SPA routing
        run: cp build/index.html build/404.html

      - name: Copy CNAME file to build directory
        run: cp CNAME build/CNAME

      - name: Deploy to production branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: production
          force_orphan: true
          commit_message: "Deploy build artifacts from ${{ github.sha }}"
