name: Deploy to Production Branch

on:
  push:
    branches: [main]
  workflow_dispatch:

# Add permissions for the GITHUB_TOKEN
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # Use a token with write permissions
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "23.5.0"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: "9.15.2"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate routes and types
        run: pnpm gen

      - name: Build for production
        run: pnpm build production
        env:
          NODE_ENV: production

      - name: Create 404.html for SPA routing
        run: cp dist/index.html dist/404.html

      - name: Copy CNAME file to build directory
        run: cp CNAME dist/CNAME

      - name: Deploy to production branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: production
          force_orphan: true
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
          commit_message: "Deploy build artifacts from ${{ github.sha }}"
