---
name: "Production PR Tests"
on:
  pull_request:
    types: [opened, synchronize]
    branches: [production]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Run tests
        run: echo "This is a dummy action. No real steps are executed."
