---
name: "Production Branch Lint"
on:
  pull_request:
    types: [opened, synchronize]
    branches: [production]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Lint step
        run: echo "This is a dummy action. No real steps are executed."
